/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class LihatPasienInap extends javax.swing.JFrame {

    /**
     * Creates new form LihatPasienInap
     */
    public LihatPasienInap() {
        initComponents();
    }

    public Object getBtnKembali() {
        return btnKembali;
    }

    public Object getBtnLogout() {
        return btnLogout;
    }

    public String getTxDokter() {
        return txDokter.getText();
    }

    public void setTxDokter(String txDokter) {
        this.txDokter.setText(txDokter);
    }

    public String getTxIdpasien() {
        return txIdpasien.getText();
    }

    public void setTxIdpasien(String txIdpasien) {
        this.txIdpasien.setText(txIdpasien);
    }

    public String getTxDiagnosa() {
        return txDiagnosa.getText();
    }

    public void setTxDiagnosa(String txDiagnosa) {
        this.txDiagnosa.setText(txDiagnosa);
    }
    
    public String getTxNama() {
        return txNama.getName();
    }

    public void setTxNama(String txNama) {
        this.txNama.setText(txNama);
    }

    public String getTxRuangan() {
        return txRuangan.getText();
    }

    public void setTxIdpetugas(String txIdpetugas) {
        this.txIdpetugas.setText(txIdpetugas);
    }
    
    public void setTxRuangan(String txRuangan) {
        this.txRuangan.setText(txRuangan);
    }

    public void addActionListener(ActionListener e){
        btnLogout.addActionListener(e);
        btnKembali.addActionListener(e);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLidPasien = new javax.swing.JLabel();
        txIdpasien = new javax.swing.JTextField();
        JLnama = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        txDokter = new javax.swing.JTextField();
        JLDokter = new javax.swing.JLabel();
        JLdiagnosa = new javax.swing.JLabel();
        JLruangan = new javax.swing.JLabel();
        txDiagnosa = new javax.swing.JTextField();
        txRuangan = new javax.swing.JTextField();
        txIdpetugas = new javax.swing.JTextField();
        JLidPetugas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lihat Pasien Inap"));

        JLidPasien.setText("ID Pasien    :");

        txIdpasien.setEditable(false);
        txIdpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdpasienActionPerformed(evt);
            }
        });

        JLnama.setText("Nama          :");

        txNama.setEditable(false);

        txDokter.setEditable(false);
        txDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDokterActionPerformed(evt);
            }
        });

        JLDokter.setText("Dokter        :");

        JLdiagnosa.setText("Diagnosa    :");

        JLruangan.setText("Ruangan    :");

        txDiagnosa.setEditable(false);
        txDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiagnosaActionPerformed(evt);
            }
        });

        txRuangan.setEditable(false);
        txRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txRuanganActionPerformed(evt);
            }
        });

        txIdpetugas.setEditable(false);
        txIdpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdpetugasActionPerformed(evt);
            }
        });

        JLidPetugas.setText("ID Petugas :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLidPasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txIdpasien))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLnama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txNama))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLDokter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txDokter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JLdiagnosa)
                        .addGap(10, 10, 10)
                        .addComponent(txDiagnosa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLruangan)
                            .addComponent(JLidPetugas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txIdpetugas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txRuangan)
                                .addGap(1, 1, 1)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLidPasien)
                    .addComponent(txIdpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnama)
                    .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLDokter)
                    .addComponent(txDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLdiagnosa)
                    .addComponent(txDiagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLruangan)
                    .addComponent(txRuangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txIdpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLidPetugas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Rumah Sakit Kurniawan");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addComponent(btnKembali)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIdpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdpasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdpasienActionPerformed

    private void txDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDokterActionPerformed

    private void txRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txRuanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txRuanganActionPerformed

    private void txIdpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdpetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdpetugasActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiagnosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDiagnosaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatPasienInap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLDokter;
    private javax.swing.JLabel JLdiagnosa;
    private javax.swing.JLabel JLidPasien;
    private javax.swing.JLabel JLidPetugas;
    private javax.swing.JLabel JLnama;
    private javax.swing.JLabel JLruangan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txDiagnosa;
    private javax.swing.JTextField txDokter;
    private javax.swing.JTextField txIdpasien;
    private javax.swing.JTextField txIdpetugas;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txRuangan;
    // End of variables declaration//GEN-END:variables
}
